### ISSUE TITLE
Actividad2ejerciciosequpo:Mayra_Felix_Daniel_Diego

### ISSUE THREAD

**Issue by Diego0501** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-mayra-diego-daniel-felix#3]
[ACTIVIDAD.2_EJERCICIOS_EQUIPO_MAYRA_DIEFO_DANIEL_FELIX.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-mayra-diego-daniel-felix/files/12553834/ACTIVIDAD.2_EJERCICIOS_EQUIPO_MAYRA_DIEFO_DANIEL_FELIX.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25/25
RESULTADOS Y CONCLUSIONES 25/25

 CALIFICACIÓN 100/100

CALIFICADO POR EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado..
